# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm for rancher
  config.vm.define "rancher" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "rancher"
    node.vm.network "private_network", ip: "172.16.10.103"
    node.vm.provision "shell", path: "setup-rancher.sh"   
  end

end
